apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-pvc
  namespace: fab-sop
spec:
  accessModes:
    - ReadWriteMany    # shared across api replicas
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-cache-pvc
  namespace: fab-sop
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
